lsi: false
safe: true

source: .
exlcude: [node_modules]

title: Github Issue Creator
email: akib.rhast@gmail.com
description: A repo to demonstrate creating github issues via a github pages site using form submission.

baseurl: ""
url:  "https://akibrhast.github.io/github-issue-submission-form/"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"