blank_issues_enabled: false
contact_links:
  - name: Project Profile Card Review and Update
    url: http://localhost:4000/
    about: Use this to update your existing project card with us or update an existing project card
